aliases:
  - &android
    components:
      - build-tools-28.0.3
      - android-29
      - extra-android-m2repository
      - extra-android-support
  
  - &android-cache
    directories:
      - ~/.cache/yarn
      - ~/.gradle/caches/modules-2
      - ~/.gradle/wrapper
  
  - &ios-cache
    directories:
      - ~/.rncache
      - ~/Library/Caches/Yarn
      - ~/Library/Caches/CocoaPods

  - &init-new-project
    |
      nvm install node
      yarn global add react-native-cli
      react-native init App --version="0.58.4"
      cd App
      yarn add react-native-baidumap-sdk@next

jobs:
  include:
    - stage: "build test for example"
      language: android
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - ./scripts/download-sdk.sh
        - nvm install node
        - npm i && npm i typescript
        - npm run build
        - cd android && TERM=dumb ./gradlew build
        - ls -lh app/build/outputs/apk/debug
        - ls -lh app/build/outputs/apk/release

#    - stage: "build test for example"
#      language: objective-c
#      os: osx
#      osx_image: xcode11.3
#      cache: *ios-cache
#      script:
#        - npm i && npm i typescript
#        - npm run build
#        - cd ios && pod install && cd ..
#        - npm run run-ios

    - stage: "build test for new project"
      language: android
      android: *android
      before_cache:
        - rm ~/.gradle/caches/modules-2/modules-2.lock
      cache: *android-cache
      script:
        - nvm install node
        - npx react-native init app && cd app
        - npm i react-native-amap3d@next
        - cd android && TERM=dumb ./gradlew build
        - ls -lh app/build/outputs/apk/debug
        - ls -lh app/build/outputs/apk/release

    - stage: "build test for new project"
      language: objective-c
      os: osx
      osx_image: xcode11.3
      cache: *ios-cache
      script:
        - npm i && npm i typescript
        - npx react-native init app && cd app
        - npm i react-native-amap3d@next
        - cd ios && pod install && cd ..
        - npx react-native run-ios

stages:
  - "test js"
  - name: "build test for example"
    if: branch = master
  - name: "build test for new project"
    if: branch = release
