platform :ios, '8.0'

target 'RNBaiduMap' do
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'DevSupport',
  ]
  pod 'react-native-baidumap-sdk', path: '../lib/ios'
end
